### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by daattali** [daattali/rstudio-addins#12]
The original repo name is `rstudio-addins` , because it was meant to just be a list of addins. But now that this list is going to evolve into a package that also lets you download the addins in the list, the package needs a name.  I want the name to ideally convey both the fat that it's a list and that it's a package for getting the addins

Suggested names so far:

- addins4rstudio 
- CLARA (Comprehensive List Archive for RStudio Add-Ins)  
- addinstallist  
- AddinStallR   
- addinaddon

**Comment by shrektan** [comment]
Honestly speaking, I think the current name "rstudio-addins" is good enough to me… I  personally prefer it than those candidates …
发自我的 iPhone

**Comment by daattali** [comment]
I don't think it's a legal name (I haven't seen any CRAN packages with a hyphen)

**Comment by ottlngr** [comment]
> both the fact that it's a list and that it's a package for getting the addins

like a catalogue? `AddinsCatalogue` or `AddinsCatalog` if you prefer AE.

**Comment by daattali** [comment]
I'll just go with a simple "addinslist"
