### ISSUE TITLE
Add a "top" and "trending" tab.

### ISSUE THREAD

**Issue by Stan125** [daattali/rstudio-addins#15]
To quickly gain an overview of the most popular and/or most recent Add-Ins, a clickable tab would be pretty cool. I don't know how one would technically implement this, though. Does anybody have an idea?

**Comment by daattali** [comment]
Thanks for the suggestion and contribution.  I'm going to close this issue though, sorry!

As I said in another thread, this isn't meant to be a full blown service providing all sorts of metrics and features.  Just a simple list of addins, and the package is just a nice touch on top of that to let you install them.  I don't want to feature creep, I want to keep the original sight of having it be a repo and not a big fancy application
